src/harvesters/_private/frontend/canvas.py
src/harvesters/core.py
src/harvesters/pfnc.py

should work for the already defined formats as before and include many others.
Can't think of a case when this would fail right now, but still: it means that many more formats would be displayed if they pass the initial "filter" (are in `component_2d_formats`).
Also I guess the component_xbit_formats lists could then be removed from pfnc.py
Tested with `mono8` and `Confidence8` so far.
For the latter it needs to be added to `component_2d_formats` instead of `component_1d_formats` as well.

more generic pixel size handling

---

src/harvesters/pfnc.py

This PR is mainly meant for discussion and basically includes #35 
Additionally it adds "support" for Confidence8 and Coord3D_C16 pixel formats.
This doesn't yet apply any nice scaling for the Coord3D_C16 format if it is a Disparity, but is already "displayable".

Support roboception formats

---

src/harvesters/core.py

When harvesters receives an incomplete Buffer the Buffer is not discard/queue. Because of this case the producer runs out of buffer.

Fix Error when harvesters receives incomplete Buffer

---

src/harvesters/core.py

Fixes: #126
According to the GenICam standard 1.4, the /// after local: should be a valid configuration.  But we need to strip it out so it doesn't affect saving the file on the local machine.
4.1.2.1 Module Register Map (Recommended)
A URL in the form “local:[///]filename.extension;address;length[?SchemaVersion=x.x.x]”
indicates that the XML description file is located in the module’s virtual register map. The
square brackets are optional.

Strip leading slashes from local: xml url

---

src/harvesters/core.py

Use the base name that is extracted from the given file path.

Resolve issue #145

---

src/harvesters/core.py

Hi Kazunari,
i tried to access the buffer information "BUFFER_INFO_TIMESTAMP", but i could only access it with direct access to the protected buffer.
The buffer provide 3 function for timestamp informations: 
- timestamp_ns() for "BUFFER_INFO_TIMESTAMP_NS"
- timestamp_frequency()
- timestamp() 
but no direct access for "BUFFER_INFO_TIMESTAMP".
I would suggest, that timestamp() returns "BUFFER_INFO_TIMESTAMP" when this is "0", it returns "BUFFER_INFO_TIMESTAMP_NS".

BUFFER_INFO_TIMESTAMP is not returned when DEVICE_INFO_TIMESTAMP_FREQUENCY is not available.

---

setup.py

Binds Harvesters version 1.3 line with the `genicam` versions < 1.2.
Once the `genicam` version is bumped to 1.2 then Harvester will have a minor version bump as well.

Restrict the genicam versions

---

src/harvesters/core.py

There was a problem for some with fetching buffers containing chunk data. I believe this is the cause of issue #269 and possibly also #276. 
The problem appears to be the buffer containing padding after the end of the chunk data and tag. To solve the issue everything in the buffer after chunk payload size can be removed since chunk payload size should point to the very end of the chunk tag, which should be at the very end of the buffer.
self._chunk_adapter.attach_buffer(buffer.raw_buffer[:buffer.delivered_chunk_payload_size]) is enough to solve the issue, however the if statment should have better performance (if slicing the buffer creates a copy of it).

_dev_alfred_issue_269_and_276

---

src/harvesters/core.py
src/harvesters/test/test_harvester_core.py

Resolve issue #277

---

src/harvesters/core.py

Resolving issue #291. Correcting units on a millisecond timeout to resolve high utilization on the background thread. A timeout in milliseconds was passed to a function expecting seconds.

Resolving #291

---

src/harvesters/core.py
src/harvesters/test/test_harvester_core.py

Introduces `timeout_on_client_fetch_call` property to distinguish it from `timeout_on_internal_fetch_call`.

Some more updates on fix for issue 289

---

src/harvesters/core.py

I have a plan to introduce a feature that securely covers custom payload types but let's use this until then.

Have a remedy for custom payload types

---

src/harvesters/core.py
src/harvesters/test/test_harvester_core.py

The change aims to allow clients to manipulate the nodes in node maps of the GenTL entities before a client instantiates an ImageAcquire object.
The use case and the primitive solution were provided by Mr. Alfred Johanesson (@Unameded); thank you very much!

Make node map exposed

---

src/harvesters/core.py

In version 1.3.6, AttributeError cannot be captured when some cameras do not have TLParamsLocked

Catch AttributeError if TLParamsLocked not exist

---

src/harvesters/core.py

This avoids exceptions when the ImageAcquirer start() fails due to DSStartAcquisition errors and buffers remains queued in the input queue.
Fixes #381

Flush buffers before revoking them while destroying an ImageAcquirer instance

---

src/harvesters/core.py

This pull request deletes the temporary created directory used for the intermediate files (XML files) loaded via register map.
It checks if the directory is empty and deletes only an empty directory.
Additional it checks if the XML file was loaded via register map or located on the host file system. In case of a local xml file, the `_remove_intermediate_file` isn't called and the file not deleted. fix #358

remove temporary directory if it is empty and check if the xml file was copied from the device

---

src/harvesters/core.py

Do not revoke the buffer results in memory leak.
fix #399
With this change I was not able to reproduce the issue (#390) which was originally addressed to be fixed by the commit (31ca2807a0668b328114d7a37e95c0bdec4412ee). As well as the commend https://github.com/genicam/harvesters/issues/390#issuecomment-1419291968 is not true. A call to `DSFlushQueue` with `ACQ_QUEUE_ALL_DISCARD` doesn't revoke the buffers.
Quote of the GenTL documentation for `ACQ_QUEUE_ALL_DISCARD`
> Discards all buffers in the input pool and the buffers in the output queue including buffers currently being filled so that no buffer is bound to any internal mechanism and all buffers may be revoked or requeued.
And the `DSAnnounceBuffer` documentation defines a required call of _revoke_
> Every call of this function must …

Revert changes from 31ca2807a0668b328114d7a37e95c0bdec4412ee

---

src/harvesters/core.py
src/harvesters/test/test_harvester_core.py

Replaced all instances of deprecated name timeout_on_client_fetch_call with timeout_period_on_client_fetch_call

Harvesters Core|Change: replaced deprecated name timeout_on_client_fetch_call

---

src/harvesters/core.py

Since the numpy version 1.14 expressions like: `if not self.data:` for checking both if the object is None and if the array is empty is deprecated and since later versions it throws a ValueError. I updated the line in represent_pixel_location() to handle later numpy versions.

fix deprecated numpy thruth value expression

---

src/harvesters/core.py

Allow cameras to work - problem described in issue #408
FLIR  cameras seem to throw an InvalidParameterException on startup to everything except `_remote_device` when registering events. This seems to allow normal functionality. I don't know if there are other unintended consequences.

Catch InvalidParameterException on registering module event listeners to work on FLIR cameras

---

src/harvesters/core.py

AcquisitionMode is recommended but not mandatory. When AcquisitionMode doesn't exist, the genicam/genapi.py:2238 will raise a AttributeError.

Fix #420, fix the Node not exsting error for AcquisitionMode
